### ISSUE TITLE
Questions about the immutable data situation in Java

### ISSUE THREAD

**Issue by frenchdonuts** [konmik/Phlux#3]
Hi konmik, I've been silently watching your libraries, and I'm a fan of your work! I have two questions concerning the immutable data situation in Java:

In the readme you say "...when we need to replace the root application variable we can reference parts of the previous root variable. What will be GC'ed is only the difference between two values which is not a problem..." Does this mean that AutoValue/AutoParcel automatically uses structural sharing when making copies?

Second question: when using AutoValue/AutoParcel, do you get fast (O(1)) structural (value-level) equality checks for free?

Thanks for taking the time to read this!

**Comment by konmik** [comment]
@frenchdonuts Hi, thanks :)

By default AutoValue/Parcel shares values when you transform a value into a builder, change some fields and build the value back. We also have https://github.com/gabrielittner/auto-value-with that can do this, but we can't use it right now because AutoValue 2.0 is not released yet (we can, but there still  some issues in it).

Considering the root variable. When building the next root variable, Phlux references the old root values, take a look here: https://github.com/konmik/Phlux/blob/master/phlux/src/main/java/phlux/Phlux.java#L96
https://github.com/konmik/Phlux/blob/master/phlux/src/main/java/phlux/Util.java#L15
it just creates a copy of the root `HashMap` with one field changed.

AutoValue/Parcel implements `equals` and `hashCode`, so when using in `HashMap` and the like, the search is optimized.

**Comment by frenchdonuts** [comment]
Thanks!
